CourseEditor/urls.py
from django.conf.urls import url

from . import views

app_name = 'CourseEditor'


urlpatterns = [
    #url(r'^', views.index, name="index"),
    url(r'^$',views.index, name='course view'),
    url(r'^course/(?P<course_id>[\w\-]+)/$', views.view_course, name='view course'),
    url(r'^course/(?P<course_id>[\w\-]+)/addStudent', views.add_student, name='add student'),

    url(r'^editCourse/(?P<course_id>[\w\-]+)/$', views.edit_course, name='edit course'),

    url(r'^addCourse/', views.add_course, name='add course'),

]

Home/urls.py
from django.conf.urls import url ,include

from . import views

app_name = 'Home'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^', include('Login.urls')),

]

Login/urls.py
from django.conf.urls import include, url

from . import views


app_name = 'Login'


urlpatterns = [
    url(r'^$', views.index, name='index'),


]

StudentArchives/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('Login.urls')),
    url(r'^studentList/', include('StudentManager.urls')),
    url(r'^courseList/', include('CourseEditor.urls')),

    url(r'^', include('Home.urls')),

]

StudentManager/urls.py
from django.conf.urls import url, include
from . import views
app_name = 'StudentManager'


urlpatterns = [
    url(r'^$', views.index, name='students view'),
    url(r'^(?P<student_id>[\w\-]+)/$', views.edit_student, name='edit student'),

]

CourseEditor/models.py
from django.db import models
import datetime

class Course(models.Model):
    course_name = models.CharField(max_length=20, default='None')
    course_code = models.CharField(max_length=20, default='None')
    course_field_names = ['course_name','course_code']


class Student(models.Model):
    student_name = models.CharField(max_length=20, default='None')
    student_last_name = models.CharField(max_length=20, default='')

    student_code = models.CharField(max_length=20, default='0000000')

    student_age = models.DateField(default=datetime.date.today)

    courses = models.ManyToManyField(Course)

    student_field_names = ['student_name','student_last_name', 'student_code','student_age']

StudentManager/models.py
from django.db import models

# Create your models here.

CourseEditor/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect

# Create your views here.
from django.shortcuts import render
from .models import Course, Student
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q


def index(request):
    all_courses = Course.objects.all()
    if request.method == 'POST':
        for course in all_courses:
            if request.POST.get('view'+str(course.id)):
                return HttpResponseRedirect('/courseList/course/' + str(course.id))
            if request.POST.get('edit'+str(course.id)):
                return HttpResponseRedirect('/courseList/editCourse/' + str(course.id))
            if request.POST.get('add_course'):
                return HttpResponseRedirect('/courseList/addCourse/' + str(course.id))
    return render(request, "CourseEditor/index.html", {'all_courses': all_courses})


def view_course(request, course_id):
    try:
        course = Course.objects.get(id=course_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        if request.POST.get('add_student'):
            return HttpResponseRedirect('/courseList/course/' + course_id + '/addStudent')
    return render(request, "CourseEditor/viewCourse.html", {'course': course, 'add_student' : 'False',
                                                            'all_students': Student.objects.filter(courses__id=course_id)})


def edit_course(request, course_id):
    try:
        course = Course.objects.get(id=course_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/')

    if request.method == 'POST':
        for name in Course.course_field_names:
            request_text = request.POST.get(name, None)
            if request_text is not None and request_text is not '':
                setattr(course, name, request_text)
                course.save()
        return HttpResponseRedirect('/courseList/')

    course.save()
    return render(request, "CourseEditor/editCourse.html", {'course': course, 'add_student' : 'True'})


def add_student(request,course_id):
    try:
        course = Course.objects.get(id=course_id)
    except ObjectDoesNotExist:
        return HttpResponseRedirect('/')
    if request.method == 'POST':
        new_student_name = request.POST.get('new_student', None)
        new_student_code = request.POST.get('new_student_code', None)

        if new_student_name == '' or new_student_name is None:
            return HttpResponseRedirect('/courseList/course/' + course_id)
        else:
            try:
                try:
                    Student.objects.get(courses__id=course_id,student_name=new_student_name.split()[0],
                                        student_last_name=new_student_name.split()[1])

                    return render(request, "CourseEditor/viewCourse.html",
                                  {'course': course,
                                   'all_students': Student.objects.all().filter(courses__id=course_id),
                                   'suggest_students': Student.objects.all().filter(~Q(courses__id=course_id)),
                                   'duplicate_student': 'True'})

                except ObjectDoesNotExist:
                    student = Student.objects.get(student_name=new_student_name.split()[0],
                                                  student_last_name=new_student_name.split()[1])
                    if new_student_code != '':
                        student.student_code = new_student_code
                    student.courses.add(course)
                    student.save()
            except ObjectDoesNotExist:
                new_student = Student()
                new_student.student_name, new_student.student_last_name = new_student_name.split()
                new_student.student_code = new_student_code
                new_student.save()
                new_student.courses.add(course)
                new_student.save()
            return HttpResponseRedirect('/courseList/course/' + course_id)

    return render(request, "CourseEditor/viewCourse.html",
                  {'course': course, 'all_students': Student.objects.all().filter(courses__id=course_id),
                   'suggest_students': Student.objects.all().filter(~Q(courses__id=course_id))})


def add_course(request):
    course = Course()
    course.course_name = "New Course"
    course.course_code = "00000"
    course.save()
    return HttpResponseRedirect('/courseList/editCourse/'+str(course.id))

Home/views.py
from django.shortcuts import render


def index(request):

    return render(request, "Home/index.html")

Login/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, "Login/editCourse.html")

StudentManager/views.py
from django.shortcuts import render, HttpResponseRedirect
from CourseEditor.models import Student
import calendar
import datetime

# Create your views here.
def index(request):
    all_students = Student.objects.all()
    if request.method == 'POST':
        for student in all_students:
            if request.POST.get('edit'+str(student.id)):
                return HttpResponseRedirect('/studentList/' + str(student.id))
    return render(request, "StudentManager/index.html", {'all_students' : all_students})


def edit_student(request,student_id):
    student = Student.objects.get(id=student_id)

    old_year = datetime.datetime.now().year-40
    test = ''
    months = []
    for i in range(1, 13):
        months.append((i, calendar.month_name[i]))
    if request.method == 'POST':
        for name in Student.student_field_names:
            request_text = request.POST.get(name, None)
            if request_text is not None and request_text is not '':
                setattr(student, name, request_text)
                student.save()

            student.student_age = student.student_age.replace(year=int(request.POST.get('student_age_year', None))+old_year,
                                                              day=int(request.POST.get('student_age_day', None)),
                                                              month=int(request.POST.get('student_age_month', None))+1)
            student.save()
    return render(request, "StudentManager/editStudent.html", {'student':student,'months':months,'current_year':old_year,'test':test})

CourseEditor/templates/CourseEditor/editCourse.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">

        <title>Course Editor</title>

    </head>
<body>
    <form method="POST" name={{course.course_name}}>
        {% csrf_token %}

        <h2>Course Code {{course_code}} + {{test}}</h2>

        <h3>Course name:</h3> <input type="text" name="course_name" placeholder="{{course.course_name}}" />
        <h3>Course code:</h3> <input type="text" name="course_code" placeholder="{{course.course_code}}" />

        <div class="item-submit-button"> <button type="submit">Save</button> </div>

    </form>
</body>

CourseEditor/templates/CourseEditor/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <form method="POST" name='list'>
         {% csrf_token %}
         {% for course in all_courses %}
         <button type = 'submit' name = 'view{{course.id}}' value = '1'>{{course.course_name}} : {{course.course_code}}</button>
         <button type = 'submit' name = 'edit{{course.id}}' value = '1'>edit</button>
         <br>
         {% endfor %}
         <button type = 'submit' name = 'add_course' value = '1'>add course</button>

    </form>
</body>
</html>

CourseEditor/templates/CourseEditor/viewCourse.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">

        <title>Course Editor</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
 <style>
  #project-label {
    display: block;
    font-weight: bold;
    margin-bottom: 1em;
  }
  #project-icon {
    float: left;
    height: 32px;
    width: 32px;
  }
  #project-description {
    margin: 0;
    padding: 0;
  }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    </head>
<body>

<h1>{{course.course_name}} : {{course.course_code}}</h1>
<h1>students : </h1>
    <form method="POST" name={{course.course_name}}>
        {% csrf_token %}
        {% if duplicate_student %}
        <script>
            alert('Student already in course');
        </script>
        {% endif %}
        {% for student in all_students %}
        <p> {{student.student_name}} {{student.student_last_name}}  :  {{student.student_code}}</p>
        {% endfor %}
        {% if add_student %}
        <button type = 'submit' name = 'add_student' value = '1'>+</button>
        {% else %}
        <script>
          $( function() {
            var projects = [
            {% for student in suggest_students %}
              {
                value: "{{student.student_name}} {{student.student_last_name}}",
                label: "{{student.student_name}} {{student.student_last_name}}",
                desc: "",
              },
              {% endfor %}

            ];

            $( "#project" ).autocomplete({
              minLength: 0,
              source: projects,
              focus: function( event, ui ) {
                $( "#project" ).val( ui.item.label );
                return false;
              },
              select: function( event, ui ) {
                $( "#project" ).val( ui.item.label );
                $( "#project-id" ).val( ui.item.value );
                $( "#project-description" ).html( ui.item.desc );
                $( "#project-icon" ).attr( "src", "images/" + ui.item.icon );

                return false;
              }
            })
            .autocomplete( "instance" )._renderItem = function( ul, item ) {
              return $( "<li>" )
                .append( "<div>" + item.label + "<br>" + item.desc + "</div>" )
                .appendTo( ul );
            };
          } );
         </script>
        <input type="text" name = 'new_student'id="project" placeholder= 'Student Name'>
        <input type="text" name = 'new_student_code' placeholder= 'Student Code'>
        <button type="submit" value="1">Save</button>
        {% endif %}


    </form>

</body>

Home/templates/Home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>Student Archives</title>
</head>
<body>
   <button href="{% url 'Login:index' %}" name = "add_course"> sdf </button>
</body>
</html>

Login/templates/Login/index.html
<!DOCTYPE html>
<html lang="en">
<form method="POST" name={{course.course_name}}>
    {% csrf_token %}

    <head>
        <meta charset="UTF-8">

        <title>Login</title>
        <h3>Course name:</h3> <input type="text" name="course_name" placeholder="{{course.course_name}}" />
        <h3>Course code:</h3> <input type="text" name="course_id" placeholder="{{course.course_code}}" />

    </head>
</form>

StudentManager/templates/StudentManager/editStudent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{student.student_name}} {{student.student_last_name}}</title>
</head>
<body>
    <form method="POST" name='succ'>

        {% csrf_token %}


        <input type="text" name="student_name" placeholder="{{student.student_name}}" />
        <input type="text" name="student_last_name" placeholder="{{student.student_last_name}}" />
        <br>
        <select name = "student_age_month">
            {% for month in months %}
                {% if forloop.counter0|add:"1" != student.student_age.month %}
                <option value="{{forloop.counter0}}">{{month}}</option>
                {% else %}
            <option selected="selected" value="{{forloop.counter0}}">{{month}}</option>

                {%endif%}
            {% endfor %}
        </select>
        <select name = 'student_age_day'>
           {% for i in "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" %}
            {% if forloop.counter0 != student.student_age.day %}
                <option value="{{ forloop.counter0 }}">{{ forloop.counter0|add:"1" }}</option>
            {% else %}
                            <option selected="selected" value="{{ forloop.counter0 }}">{{ forloop.counter0|add:"1" }}</option>
            {% endif %}

           {% endfor %}
        </select>

        <select name = 'student_age_year'>
           {% for i in "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" %}
                {% if current_year|add:forloop.counter0 != student.student_age.year %}
                    <option value="{{ forloop.counter0 }}">{{ forloop.counter0 }} : {{current_year|add:forloop.counter0 }}</option>
                {% else %}
                    <option selected="selected" value="{{ forloop.counter0 }}">{{ forloop.counter0 }} : {{current_year|add:forloop.counter0 }}</option>
                {% endif %}
           {% endfor %}
        </select>

        <div class="item-submit-button"> <button type="submit">Save</button> </div>
    </form>
</body>
</html>

StudentManager/templates/StudentManager/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Student List</title>
</head>
<body>
    <form method="POST" name={{course.course_name}}>
    {% csrf_token %}

    {% for student in all_students %}
        <button type = 'submit' name = 'edit{{student.id}}' value = '1'>{{student.student_name}} {{student.student_last_name}}</button>
    <br>
    {% endfor %}
        </form>
</body>
</html>